# Generated by Django 3.1.1 on 2020-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobattachment',
            name='file',
            field=models.FileField(storage='db_file_storage.storage.DatabaseFileStorage', upload_to='images.UploadedImage/bytes/filename/mimetype'),
        ),
    ]
